#!/usr/bin/env python

from time import sleep

file = open("gpsbabel_test_data.txt")

while 1:
    group = ''
    for i in range(0,6):
      line = file.readline()
      if not line:
          break
      group += line
    print group
    sleep(1)    
