#!/usr/bin/env python

from time import sleep
import sys
import os

file = open(os.path.abspath( __file__ ) + "_test_data.txt")
while 1:
    group = ''
    for i in range(0,6):
      line = file.readline()
      if not line:
          break
      group += line
    print group
    sys.stdout.flush()
    sleep(1)    
